# Generated by Django 4.2 on 2023-04-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.CharField(max_length=100, verbose_name='Quantidade'),
        ),
    ]
